"use client";
import React from "react";

const PrivacyPolicyPage = () => {
  const sections = [
    {
      id: "general",
      title: "1. General",
      content: [
        {
          subtitle: "1.1",
          text: `Welcome to LAFETCH ("Site" or "Platform"). The website www.la-fetch.com and mobile application Lafetch available on Apple and Android App Store is owned and operated by AS10 Techretail Pvt Ltd ("Lafetch"), a company incorporated under the provisions of the Companies Act, 2013 with its registered office at 122, First Floor, Universal Trade Tower, Sohna Road, Omaxe City Centre, Sector-49, Manesar, Gurugram, Haryana, 122101. You may be accessing our Site from a computer or mobile phone device (through an iOS or Android application) and this Privacy Policy will govern your use of our Site and your conduct, regardless of the means of access.

Through the Platform, Lafetch inter alia facilitates the sale and purchase of a diverse range of fashion, home, lifestyle and other products and services listed on and sold on the Platforms from time to time ("Products") to the users of the Platforms ("User" or "Users" or "you" or "your"). The term User/User(s) means any individual or entity which uses, accesses or browses the Platform and/or purchases Products from the Platform.`,
        },
        {
          subtitle: "1.2",
          text: `Lafetch is committed to protecting and respecting your privacy. This privacy policy ("Privacy Policy"), together with the Lafetch Terms and Conditions ("Terms of Use") and all other policies notified by us from time to time governs your use of the Platforms. This Privacy Policy describes our policies and procedures on the collection, use, disclosure, sharing, processing, transfer storage, retention and safeguarding of the Information (defined hereinafter) provided to us by you through the use of the Platforms and/or pursuant to the purchase of the Products on the Platforms.`,
        },
      ],
    },
    {
      id: "applicability",
      title: "2. Applicability of the Privacy Policy",
      content: [
        {
          subtitle: "2.1",
          text: `By using, browsing, accessing, or purchasing Products from the Platforms and/or by submission of Information (and in case of a minor - submission of such minor's Information either by the parents or the legal guardian), you agree to be bound by the terms of this Privacy Policy and consent to the collection, use, storage, possession, dealing, processing, handling, sharing, disclosure, transfer or retention of your Information in accordance with the terms of the Privacy Policy and agree to be governed by the laws of India including but not limited to the laws applicable to data protection and privacy. We shall not use the User's Information in any manner except as provided under this Privacy Policy and to the extent permitted under the laws applicable to data protection and privacy. All capitalized terms used herein if not defined shall have the same meaning as ascribed to them under the Terms of Use.`,
        },
        {
          subtitle: "2.2",
          text: `You may be able to access or browse the Platforms from outside the geographical territories of the Republic of India, however please note that the Products listed on the Platform are not offered for sale outside the geographical territories of the Republic of India. Your Information will primarily be collected, stored and processed in India and will be governed by the applicable laws (including data protection and privacy laws) that are different from those that apply in the country in which you are located.`,
        },
        {
          subtitle: "2.3",
          text: `This document is an electronic record and is governed by the provisions under the Information Technology Act, 2000 and rules made thereunder as may be applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.`,
        },
        {
          subtitle: "2.4",
          text: `You may be asked to provide your information anytime you visit, access, use or browse the Platforms. We may share information and use it consistent with the provisions of this Privacy Policy. We may also combine it with other information to provide and improve our Products, services, content and advertising. Please take a moment to familiarize yourself with our Privacy Policy. If you do not agree with any provisions of the Terms or this Privacy Policy, we advise you to not use or access the Platforms.`,
        },
      ],
    },
    {
      id: "information-collected",
      title: "3. Type of Information Collected",
      content: [
        {
          subtitle: "3.1",
          text: `This Privacy Policy sets out the type of Information collected from the Users, including the nature of the Sensitive Personal Data/Information (defined hereinafter), the purpose, means and modes of usage of such Information and how and to whom we shall disclose, share or transfer such Information. You may at any time withdraw your consent for collection and use of your Information including Personal Information (defined hereinafter) or Sensitive Personal Data/Information. However, please note that if you withdraw your consent, we may no longer be able to provide you with the corresponding service for which you have withdrawn your consent. It is hereby clarified that your decision to withdraw your consent will not affect the processing of Information based on your previous consent prior to the withdrawal.`,
        },
        {
          subtitle: "3.2",
          text: `We may collect a variety of Information from you, including your name, mailing address, phone number, email address and contact preferences, including any other usage and interaction details with us or our affiliates. We may collect such information which when combined with other pieces of information available with us could reasonably allow you to be identified ("Personal Information"). Personal Information shall include but is not limited to your full name, personal contact numbers, residential address, email address, gender, date of birth. Personal Information can be in any format including but not limited to photographs or documents.

We may also collect such Non-Personal Information which when clubbed with Personal Information shall be treated as Personal Information. Non-Personal Information includes data or information that doesn't personally identify you and may include hardware identifiers, unique systems or application software etc.`,
        },
        {
          subtitle: "3.3",
          text: `We may also collect, receive, process or store certain sensitive personal data/information provided by you which may consist of, but not be limited to:
          
(a) Password;
(b) Financial information such as bank account or credit card or debit card or other payment instrument details;
(c) Any detail relating to (a) and (b) above as provided to us for providing the Products and/or processing your orders placed with us on the Platform; and
(d) Any of the information received under (a) and (b) above by us for processing or storing under lawful contract or otherwise.

(Collectively, referred to as "Sensitive Personal Data/Information").

Personal Information and Sensitive Personal Data/Information are collectively referred to as "Information".`,
        },
        {
          subtitle: "3.4",
          text: `You agree to provide information, which shall be true, correct, up to date and accurate. You may access, amend, alter or require deletion of your information partially or fully by contacting us at customersupport@la-fetch.com`,
        },
        {
          subtitle: "3.5",
          text: `The Platforms are not directed towards minors. We do not knowingly collect Personal Information from any User who is under 18 (Eighteen) years. If we are made aware that we have collected the Personal Information of a person below the age of 18 (Eighteen) years, we will take steps to delete the Information within a reasonable time frame. If a parent or legal guardian becomes aware that his or her child has provided his/her Information on the Platforms without their consent, he or she shall contact us for the deletion of such Information. In the event, where in contravention to the Privacy Policy and Terms of Use, a person below the age of 18 (Eighteen) uses the services, we shall not be held liable or responsible for any damage or injury suffered by such person.`,
        },
        {
          subtitle: "3.6",
          text: `Location Information: We may also collect information related to your location through Bluetooth and Wifi signals or other technologies. In order to collect geo-location information, the location settings must be enabled on your Device. Therefore, in some cases, the Platform may request that you enable the location settings. Except in cases where any specific services requested by you require or involve personal identification, the Platform collects location data anonymously and in a form that does not personally identify you.`,
        },
        {
          subtitle: "3.7",
          text: `Other Information: The Platform also may collect other information about you in ways that the Platform describe to you or otherwise with your consent like the permission to access your location, camera usage microphone access etc. You can choose not to provide us with certain types of information, but doing so may affect your ability to avail and/or use some services on the Platform.`,
        },
      ],
    },
    {
      id: "use-of-information",
      title: "4. Use of Information Collected",
      content: [
        {
          subtitle: "4.1",
          text: `We may collect Information, whenever relevant, to help provide you with information and to complete or process any transaction or display any Product you have requested or to participate in any online event or contest. You also consent to the collection of certain Information or document as per the applicable laws in the course of your purchasing the Products on the Platform.`,
        },
        {
          subtitle: "4.2",
          text: `We may collect, use or process your information including Personal Information and Sensitive Personal Data/Information for the following purposes:`,
          subpoints: [
            "4.2.1 For creating and giving you access to your registered account on the Platforms.",
            "4.2.2 To validate and process your request for the provision of Products or accessing of the Platforms.",
            "4.2.3 To assist merchants to handle and fulfil your orders.",
            "4.2.4 To develop, deliver, process and improve our Products, services, content in order to personalize and improve your experience.",
            "4.2.5 To inform you about our Products and/or third-party products, services, offers, discounts, updates, promotional initiatives, upcoming events, that may be of your interest, including providing you information in relation to your order confirmations, invoices, delivery status, technical notices, security alerts, etc.",
            "4.2.6 For our internal business analytical and research purposes such as auditing, data analysis and research to improve our Products, services and customer communications.",
            "4.2.7 To meet any legal or regulatory requirement or comply with a request from any governmental or judicial authority.",
            "4.2.8 To provide you with recommendation about Products you may be interested in, based on your use of the Platforms or browsing behavior.",
            "4.2.9 To provide you with marketing communications and advertising that we believe may be of interest for you.",
            "4.2.10 To resolve any request, dispute, grievance or complaint raised by you in relation to your use of the Platforms.",
            "4.2.11 To detect or monitor any fraudulent or illegal activity on the Platforms.",
            "4.2.12 To facilitate software updates, product support, improve the Platform experience and services therein and to verify compliance with the terms of this Policy.",
          ],
        },
        {
          subtitle: "4.2.11",
          text: `Convenience Fee Processing: As part of the order placement and payment process, Lafetch shall collect and process a non-refundable Convenience Fee. This fee covers various administrative and operational costs, including secure payment processing, customer support, technology maintenance, and express shipping coordination. Payment-related information, including the Convenience Fee, may be shared with our payment gateway providers and financial institutions solely for the purpose of facilitating the transaction. By placing an order on the Platform, you expressly consent to the collection, processing, and storage of such information for the purposes of Convenience Fee application and payment processing.`,
        },
        {
          subtitle: "4.3",
          text: `When you use our voice, image and camera services, we use your voice input, images, videos, and other Information to respond to your requests, provide the requested Products to you, and improve our services or the Platform.`,
        },
        {
          subtitle: "4.4",
          text: `The Platform transmits, collects, maintains, processes and use the location data and information to provide and improve the design, functionality, performance, and content of the Platform`,
        },
      ],
    },
    {
      id: "disclosure-sharing",
      title: "5. Disclosure and/or Sharing of Information Collected",
      content: [
        {
          subtitle: "5.1",
          text: `We may from time to time be required to disclose the Information collected from you to our trusted third-party service providers who assist us in order to facilitate the provision of certain services in relation to your purchase of Products on the Platforms. For instance, we may share your information with third party payment gateway provider to process your online transactions on the Platforms or with logistic service providers for delivery of the Products purchased on the Platform. By using the Platforms and/or purchasing Products on the Platform, you consent to our disclosure of your Information with third party service providers in manner as mentioned in this Privacy Policy. We ensure that such third-party service providers are bound by reasonable confidentiality obligations and/or use, maintain and follow generally accepted industry and security standards commensurate with the security standards set forth in this Privacy Policy with respect to such Information.`,
        },
        {
          subtitle: "5.2",
          text: `The Information collected from you may be shared with our affiliates for seamless shopping experience on our Platforms. By continuing to use our Platform and purchase of Products and services offered by us on the Platforms, you hereby consent to share and store Information with our affiliates for the purposes of providing a seamless shopping experience and continued services. We are committed to safeguarding your privacy and ensuring the security of your Information.`,
        },
        {
          subtitle: "5.3",
          text: `To the extent permitted under the applicable laws, we may also disclose your Information with external organization or individuals if we have reasons to believe that the access, use, preservation or disclosure of the Information is reasonably necessary to:`,
          subpoints: [
            "5.3.1 Meet the requisitioned under any applicable laws, regulations, legal processes, judicial decree or other enforceable governmental request/order/notice which in our sole discretion, is deemed necessary in order to protect our rights or the rights of other Users of the Platform; or",
            "5.3.2 Detect, prevent or otherwise address fraud, security or technical issues; or",
            "5.3.3 Fight fraud and credit risk.",
          ],
        },
        {
          subtitle: "5.4",
          text: `We may also disclose or transfer your Information to any third party as a part of reorganization or a sale of the assets, division or transfer of a part or whole of us. We shall ensure that third party to which we transfer or sell our assets will have appropriate confidentiality and security measures, at least as protective as those described in this Privacy Policy, to handle your Information. You will have the opportunity to opt out of any such transfer if the new entity's planned processing of your Information differs materially from that set forth in this Privacy Policy.`,
        },
        {
          subtitle: "5.5",
          text: `A third-party payment gateway provider may be required to collect certain financial information from you including, but not restricted to, your credit/debit card number or your bank account details (collectively referred to as "Financial Information"). All Financial Information collected from you by such third-party payment gateway providers will be used only for billing and payment processes. The Financial Information collected from you is transacted through secure digital platforms of approved payment gateways which are under encryption, thereby complying with reasonably expected technology standards. The verification of the Financial Information shall be accomplished only by you through a process of authentication in which we shall have no role to play and hence, we shall bear no liability in relation to the same. We shall neither be liable nor responsible for any actions or inactions of third-party payment gateway providers or any breach of conditions, representations and warranties given by them. We shall also not be obligated to mediate or resolve any dispute or disagreement between you and such third-party payment gateway providers.`,
        },
        {
          subtitle: "5.6",
          text: `While we take best efforts to ensure that your Information including Personal Information, Financial Information and Sensitive Personal Data/Information is duly protected by undertaking security measures prescribed under applicable laws, you are strongly advised to exercise reasonable discretion while providing Personal Information or Financial Information and Sensitive Personal Data/Information while using the services given that the Internet is susceptible to security breaches.`,
        },
        {
          subtitle: "5.7",
          text: `The Information shared and stored may include, but is not limited to, your name, contact details, purchase history, preferences, saved addresses, phone numbers, payment information, and browsing behavior.`,
        },
        {
          subtitle: "5.8",
          text: `We may disclose and share Non-Personal Information to any such partner or third-party developers to improve their software, hardware and services designed for use with the Platform, we may also provide any such partner or third-party developer with a subset of diagnostic information that is relevant to that partner's or developer's software, hardware and/or services, as long as the diagnostic information is in a form that does not personally identify you.`,
        },
      ],
    },
    {
      id: "retention",
      title: "6. Retention of Information",
      content: [
        {
          text: `We will retain your information and any data for the period necessary to fulfil the purposes outlined in this Privacy Policy unless a longer retention period is required or permitted under the applicable law.`,
        },
      ],
    },
    {
      id: "storage",
      title: "7. Storage",
      content: [
        {
          text: `The Information collected on the Platform shall be stored and processed in India and shall be governed by the applicable laws of India (including data protection and privacy laws)`,
        },
      ],
    },
    {
      id: "security",
      title: "8. Security",
      content: [
        {
          subtitle: "8.1",
          text: `The security of your Personal Information is important to us. We have implemented security policies, rules and technical measures, as required under applicable law including firewalls, transport layer security and other physical and electronic security measures to protect the Personal Information that it has under its control from unauthorized access, improper use or disclosure, unauthorized modification and unlawful destruction or accidental loss. When you submit your information on the Platforms, your information is protected through our security systems. Please note that we use international and industry-recognized standards such as per applicable laws, rules and regulations.`,
        },
        {
          subtitle: "8.2",
          text: `Your information is contained within secured networks and is only accessible by a limited number of authorized persons who have access rights to such systems or otherwise require such information for the purposes provided in this Privacy Policy. These authorized persons are also under an obligation to keep such information confidential.`,
        },
        {
          subtitle: "8.3",
          text: `Although we make best possible efforts to transmit and store all the information provided by you in a secure operating environment that is not open to public, you understand and acknowledge that there is no such thing as complete security and we do not guarantee that there will be no unintended disclosures of any information and potential security breaches. You agree not to hold us responsible for any breach of security or for any action of any third parties that receive your Personal Information or events that are beyond our reasonable control including, acts of government, computer hacking, unauthorized access to computer data and storage device, computer crashes, technical glitches, breach of security and encryption, etc.`,
        },
      ],
    },
    {
      id: "cookies",
      title: "9. Cookies Policy",
      content: [
        {
          subtitle: "9.1",
          text: `Due to the communications standards on the Internet, when you visit, access or browse the Platforms, we automatically receive the uniform resource locator of the site from which you visit, access or browse the Platforms, details of the website you visit on leaving the Platforms, the internet protocol ("IP") address of each User's computer operating system, type of web browser the User is using, email patterns, and the name of the User's internet service provider. This information is used solely to analyse overall User trends and to help us improve our services. Please note that the link between the User's IP address and the User's personally identifiable information is not shared with third parties without such User's permission or except when required by law or to provide or facilitate the User with the services. Notwithstanding the above, the User acknowledges that we reserve the right to share some of the aggregate findings, including the personal information provided by the Users in an unidentifiable, aggregate form, and not the specific data with advertisers, sponsors, investors, strategic partners, and others in order to help grow the business. The amount of information sent to us depends on the settings of the web browser used by the User to access the Platforms. The User may refer to the browser used, if the User wishes to learn what information is provided to us.`,
        },
        {
          subtitle: "9.2",
          text: `The Platforms use temporary cookies to store certain data. We do not store Personal Information in the cookies. Information collected by us, by any means whatsoever, that does not personally identify the User as an individual (such as patterns of utilization described above) is exclusively owned by us and may be used by us and third-party service providers for technical administration of the Platforms, user administration, research, development, and other purposes.`,
        },
        {
          subtitle: "9.3",
          text: `You understand that you may set or amend your web browsers to delete or disable cookies. If you choose to disable cookies on your computer or mobile telecommunication device, it may impair, degrade or restrict access to certain areas of the Platforms.`,
        },
        {
          subtitle: "9.4",
          text: `We may allow other companies or entities to serve advertisements to you. These companies or entities include third party advertisement servers, advertisement agencies, advertisement technology vendors and research firms. We may target some advertisements to you that fit a certain general profile. We do not use Personal Information to target advertisements to you. In the course of serving advertisements or optimizing the services to its Users, we may allow authorised third parties to place or recognize a unique cookie on the User's browser.`,
        },
        {
          subtitle: "9.5",
          text: `You agree and understand that we do not exercise control over third party websites displayed as search results or links on the Platforms. These other sites may place their own cookies or other files on the Users' computer, collect data or solicit personal information from the Users, on which we have no control and shall not be held responsible or liable. We do not make any representations concerning the privacy practices or policies of such third parties or terms of use of such websites, nor do we guarantee the accuracy, integrity, or quality of the information, data, text, software, sound, photographs, graphics, videos, messages or other materials available on such websites. The inclusion or exclusion does not imply any endorsement by us of such websites, the websites' provider, or the information on the website.`,
        },
        {
          subtitle: "9.6",
          text: `We may keep records of telephone calls received from and made to Users for the purpose of administration of services, research and development, training, business intelligence, business development, or for User administration. We may share such telephone records with third parties when required by law or when required to provide or facilitate the User with the services.`,
        },
        {
          subtitle: "9.7",
          text: `You consent to our reproduction/publishing of all testimonials and reviews given by you on the Platforms in relation to the services or the Products. You agree that we may edit the testimonials and reviews provided by you and reproduce/publish such edited or paraphrased versions of the testimonials and reviews on the Platforms. If the User has any concerns with the reproduction/publication of any testimonial or review provided by you, the User may contact us at customersupport@la-fetch.com`,
        },
      ],
    },
    {
      id: "opt-out",
      title: "10. Opt-Out Policy",
      content: [
        {
          subtitle: "10.1",
          text: `The third-party service providers with whom we may share Information provided by you are not permitted to market their own services or send promotional e-mails or engage in promotional communication with you. We provide you with the opportunity to opt-out of receiving non-essential, promotional, or marketing-related communication from us or our third-party partners.`,
        },
        {
          subtitle: "10.2",
          text: `If you wish to remove your contact information from all our mailing lists and newsletters, you can click on the "unsubscribe" link or follow the instructions in each e-mail message. Alternatively, you can contact us at customersupport@la-fetch.com. We reserve the right to limit membership based on availability of contact information. All Users will be notified by email prior to any actions taken.`,
        },
      ],
    },
    {
      id: "changes",
      title: "11. Change/Modification/Amendment to Privacy Policy",
      content: [
        {
          text: `This Privacy Policy is subject to changes, modifications and amendments and we reserve the right to make to changes, modifications and amendments based on business, legal or regulatory requirements. The Privacy Policy, as and when changed, modified and amended, shall be updated on the Platforms. While we make all reasonable efforts to communicate any significant changes to this Privacy Policy to you on best effort basis, we encourage you to review this Privacy Policy whenever you visit our Platforms to understand how your Information is used. Your continued use of the Platforms after any changes, modifications and amendments to this Privacy Policy will be deemed as your acceptance to such changes, modifications and amendments.`,
        },
      ],
    },
    {
      id: "governing-law",
      title: "12. Governing Law",
      content: [
        {
          text: `The terms of this Privacy Policy shall be governed and construed in accordance with the laws of India. Any dispute regarding or arising out of this Privacy Policy shall be subject to the jurisdiction of the courts in New Delhi and/or Haryana.`,
        },
      ],
    },
    {
      id: "severability",
      title: "13. Severability",
      content: [
        {
          text: `Whenever possible, each section of this Privacy Policy shall be interpreted in a manner so as to be valid under applicable law. However, in the event any provision is held to be prohibited or invalid, such provision shall be ineffective only to the extent of such prohibition or invalidity, without invalidating the remainder of such provision or other remaining provisions of this Privacy Policy.`,
        },
      ],
    },
    {
      id: "grievance",
      title: "14. Grievance Redressal",
      content: [
        {
          text: `In case you have any questions, grievance or complaints about this Privacy Policy, or the Platforms, you may contact our grievance officer on the below mentioned details:`,
          contact: {
            name: "Maneet Oberoi",
            designation: "Legal Counsel",
            email: "legal@la-fetch.com",
          },
        },
      ],
    },
  ];

  return (
    <div className="min-h-screen bg-white">
      {/* <Navbar /> */}

      {/* Hero Section */}
      <div className="bg-[#0f1110] text-white py-16 md:py-24">
        <div className="max-w-5xl mx-auto px-6">
          <h1 className="text-4xl md:text-5xl font-semibold tracking-tight">
            Privacy Policy
          </h1>
          <p className="text-gray-300 mt-4 max-w-3xl">
            Your privacy is important to us. Learn how LAFETCH protects your
            data and how we use the information you share with us.
          </p>
        </div>
      </div>

      {/* Main Content */}
      <div className="max-w-4xl mx-auto px-6 py-12">
        {sections.map((section) => (
          <section key={section.id} id={section.id} className="mb-12">
            <h2 className="text-3xl font-bold text-gray-900 mb-6">
              {section.title}
            </h2>

            <div className="space-y-6">
              {section.content.map((item, idx) => (
                <div key={idx} className="space-y-3">
                  {item.subtitle && (
                    <h3 className="font-semibold text-gray-900 text-lg">
                      {item.subtitle}
                    </h3>
                  )}

                  {item.text && (
                    <p className="text-gray-700 leading-relaxed whitespace-pre-wrap">
                      {item.text}
                    </p>
                  )}

                  {item.subpoints && (
                    <ul className="space-y-2 ml-6 list-disc text-gray-700">
                      {item.subpoints.map((point, i) => (
                        <li key={i} className="leading-relaxed">
                          {point}
                        </li>
                      ))}
                    </ul>
                  )}

                  {item.contact && (
                    <div className="  p-6 rounded-lg mt-6">
                      <strong className="text-gray-900 block mb-3 text-lg">
                        Contact Information:
                      </strong>
                      <div className="space-y-2 text-gray-700">
                        <p>
                          <b>Name:</b> {item.contact.name}
                        </p>
                        <p>
                          <b>Designation:</b> {item.contact.designation}
                        </p>
                        <p>
                          <b>Email:</b>{" "}
                          <a
                            href={`mailto:${item.contact.email}`}
                            className="text-blue-600 hover:underline"
                          >
                            {item.contact.email}
                          </a>
                        </p>
                      </div>
                    </div>
                  )}
                </div>
              ))}
            </div>
          </section>
        ))}
      </div>

      {/* <Footer /> */}
    </div>
  );
};

export default PrivacyPolicyPage;
