export const endPoints = {
  getProducts: "/products?status=1",
  auth: "/auth/sign-up-send-otp",
  signin: "/auth/sign-in-send-otp",
  verifyOtp: "/auth/verify-otp",
  resendOtp: "/auth/resend-otp",
  updateUser: "/auth/update-user-profile",
  getCollection: "/collection-with-products",
  getCategories: "/categories",
  getBanners: "/banners",
  getBlogs: "/get-blogs",
  getBoards: "/wishlist-board",
  addBoard: "/wishlist-board",
  addProductToBoard: "/board-product",
  productdetialsbyid: "/product",
  addProductToCart: "/add-to-cart",
  deleteBoard: "/wishlist-board",
  editBoard: "/wishlist-board",
  getBoardsProducts: "/board-products",
  deleteBoardProduct: "/board-product",
  productSuggestion: "/product-suggestion",
  productSearch: "/product-search",
  deleteCartItem: "/cart-item",
  getCoupons: "/coupons",
};
